#!/usr/bin/env python3
"""
build_index.py — regenerate glossary/INDEX.md and glossary/terms.yaml
from the YAML frontmatter of every glossary entry.

The frontmatter in each glossary/*.md file is the single source of truth for
locked terms. This script derives two things from it:

  glossary/INDEX.md    a human lookup table: character -> rendering -> entry
  glossary/terms.yaml  the machine-readable locks, for tools/check_locks.py

Run after adding or changing a glossary entry:

    python3 tools/build_index.py

Chapter lists are recomputed from source/chinese.md, so they cannot drift
out of date. Everything else comes from the entry's own frontmatter.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GLOSSARY = ROOT / "glossary"
SOURCE = ROOT / "source" / "chinese.md"


def parse_frontmatter(text):
    """Minimal YAML frontmatter reader — no external dependency."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    data, covers = {}, []
    in_covers = False
    for line in m.group(1).split("\n"):
        if line.startswith("covers:"):
            in_covers = True
            continue
        if in_covers and line.strip().startswith("- {"):
            c = re.search(r'char:\s*"([^"]*)"', line)
            r = re.search(r'render:\s*"([^"]*)"', line)
            if c:
                covers.append((c.group(1), r.group(1) if r else ""))
            continue
        in_covers = False
        km = re.match(r"^(\w+):\s*(.*)$", line)
        if not km:
            continue
        key, raw = km.group(1), km.group(2).strip()
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            data[key] = [v.strip().strip('"') for v in inner.split(",") if v.strip()]
        else:
            data[key] = raw.strip('"')
    data["covers"] = covers
    return data


def chapters_for(term, by_chapter):
    return [n for n in sorted(by_chapter) if term and term in by_chapter[n]]


def load_chapters():
    if not SOURCE.exists():
        return {}
    parts = re.split(r"^## Chapter (\d+)$", SOURCE.read_text(encoding="utf-8"), flags=re.M)
    return {int(parts[i]): parts[i + 1] for i in range(1, len(parts), 2)}


def main():
    by_chapter = load_chapters()
    entries = []
    for path in sorted(GLOSSARY.glob("*.md")):
        if path.name in ("INDEX.md", "TRIAGE.md"):
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            print(f"  ! no frontmatter: {path.name}", file=sys.stderr)
            continue
        fm["file"] = path.name
        # recompute chapters from the corpus where we can
        primary = fm.get("term", "").split(" & ")[0].strip()
        found = chapters_for(primary, by_chapter)
        if found:
            fm["chapters"] = [str(n) for n in found]
        entries.append(fm)

    # sort by breadth of reach, then by term
    entries.sort(key=lambda e: (-len(e.get("chapters", [])), e.get("term", "")))

    # ---------- INDEX.md ----------
    out = [
        "# Glossary index",
        "",
        "*Generated by `tools/build_index.py` from the frontmatter of each entry.*",
        "**Do not edit by hand** — regenerate instead:",
        "",
        "```bash",
        "python3 tools/build_index.py",
        "```",
        "",
        f"**{len(entries)} entries.** Sorted by how much of the book each term touches.",
        "",
        "| Term | Say | Render as | Never | Chapters | Entry |",
        "|---|---|---|---|---|---|",
    ]
    for e in entries:
        never = ", ".join(f'"{x}"' for x in e.get("forbidden", [])) or "—"
        chs = e.get("chapters", [])
        span = f"{len(chs)}" if chs else "—"
        out.append(
            f'| **{e.get("term","")}** | *{e.get("pinyin","")}* | {e.get("render","")} '
            f'| {never} | {span} | [`{e["file"]}`]({e["file"]}) |'
        )

    covered = [(c, r, e) for e in entries for c, r in e.get("covers", [])]
    if covered:
        out += [
            "",
            "## Secondary characters",
            "",
            "*Terms treated inside another entry rather than given one of their own, "
            "so that a lookup never dead-ends.*",
            "",
            "| Character | Render as | Treated in |",
            "|---|---|---|",
        ]
        for c, r, e in sorted(covered):
            out.append(f'| **{c}** | {r} | [`{e["file"]}`]({e["file"]}) — {e.get("term","")} |')

    out += [
        "",
        "## Still open",
        "",
        "Terms not yet given an entry are listed in [`TRIAGE.md`](TRIAGE.md), "
        "with their frequency in the text and the order they are being worked in.",
        "",
    ]
    (GLOSSARY / "INDEX.md").write_text("\n".join(out), encoding="utf-8")

    # ---------- terms.yaml ----------
    y = [
        "# Locked terms — generated by tools/build_index.py. Do not edit by hand.",
        "# Source of truth: the frontmatter of each glossary/*.md entry.",
        "",
    ]
    for e in entries:
        y.append(f'- term: "{e.get("term","")}"')
        y.append(f'  pinyin: "{e.get("pinyin","")}"')
        y.append(f'  render: "{e.get("render","")}"')
        y.append(f'  forbidden: [{", ".join(chr(34)+x+chr(34) for x in e.get("forbidden", []))}]')
        y.append(f'  chapters: [{", ".join(e.get("chapters", []))}]')
        y.append(f'  status: {e.get("status","open")}')
        y.append(f'  entry: glossary/{e["file"]}')
        for c, r in e.get("covers", []):
            y.append(f'  # covers {c} -> {r}')
        y.append("")
    (GLOSSARY / "terms.yaml").write_text("\n".join(y), encoding="utf-8")

    print(f"wrote glossary/INDEX.md and glossary/terms.yaml ({len(entries)} entries, "
          f"{len(covered)} secondary characters)")


if __name__ == "__main__":
    main()
